# Get all Observations for Surface

SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_su:  <http://w3id.org/glosis/model/v1.0.0/surface#>
SELECT ?obs ?rest
WHERE {
    ?obs rdfs:subClassOf sosa:Observation .
    ?obs rdfs:subClassOf ?rest .
    ?rest owl:onProperty sosa:hasFeatureOfInterest .
    ?rest owl:allValuesFrom glosis_su:GL_Surface .
}
;

# Get all restrictions marking surface as FoI
SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_su:  <http://w3id.org/glosis/model/v1.0.0/surface#>
SELECT ?rest ?o ?type
WHERE {
    ?rest owl:onProperty sosa:hasFeatureOfInterest .
    ?rest owl:allValuesFrom glosis_su:GL_Surface .
    ?o rdfs:subClassOf ?rest .
    ?o a ?type .
}
;


# Get restrictions for a particular property

SPARQL
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_sp:  <http://w3id.org/glosis/model/v1.0.0/siteplot#>
SELECT ?p ?s
WHERE {
    glosis_sp:CropClass rdfs:subClassOf ?rest .
    ?rest owl:onProperty sosa:hasFeatureOfInterest.
    ?rest owl:allValuesFrom ?u .
    ?u owl:unionOf ?set . 
#    ?set rdf:first ?o .
    ?set ?p ?s
}
;

# Get all code-list names for Surface

SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_su:  <http://w3id.org/glosis/model/v1.0.0/surface#>
SELECT ?rest_c ?code_list
WHERE {
    ?obs rdfs:subClassOf sosa:Observation .
    ?obs rdfs:subClassOf ?rest .
    ?obs rdfs:subClassOf ?rest_c .
    ?rest owl:onProperty sosa:hasFeatureOfInterest .
    ?rest owl:allValuesFrom glosis_su:GL_Surface .
    ?rest_c owl:onProperty sosa:hasResult .
    ?rest_c owl:allValuesFrom | owl:someValuesFrom ?code_list .
}
;



