# Physio-chemical properties
SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#> 
PREFIX glosis_lh:  <http://w3id.org/glosis/model/v1.0.0/layerhorizon#>
SELECT DISTINCT ?query
WHERE {
    ?obs rdfs:subClassOf  glosis_lh:PhysioChemical .
    ?obs rdfs:subClassOf ?rest_p .
    ?rest_p owl:onProperty sosa:observedProperty .
    ?rest_p owl:hasValue ?prop .
    ?prop skos:prefLabel ?label
    BIND (CONCAT('INSERT INTO core.property_phys_chem (label, uri) VALUES (\'', ?label,
          '\', \'', ?prop, '\');') AS ?query)
};


# Units of measure
SPARQL
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/v1.0.0/layerhorizon#>
SELECT DISTINCT ?query
#SELECT DISTINCT ?unit ?label
WHERE {
    ?value rdfs:subClassOf glosis_lh:PhysioChemicalValue .
    ?value rdfs:subClassOf ?rest .
    ?rest owl:onProperty qudt:unit .
    ?rest owl:hasValue ?unit .
    ?unit rdfs:label ?label .
    FILTER(lang(?label) = 'en') .
    BIND (CONCAT('INSERT INTO core.unit_of_measure (label, uri) VALUES (\'', ?label,
         '\', \'', ?unit, '\');') AS ?query)
};




## Aid queries

SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#> 
PREFIX glosis_lh:  <http://w3id.org/glosis/model/v1.0.0/layerhorizon#>
SELECT ?obs ?prop ?proc
WHERE {
    ?obs rdfs:subClassOf  glosis_lh:PhysioChemical .
    ?obs rdfs:subClassOf ?rest_p .
    ?obs rdfs:subClassOf ?rest_m .
    ?rest_p owl:onProperty sosa:observedProperty .
    ?rest_p owl:hasValue ?prop .
    ?rest_m owl:onProperty sosa:usedProcedure .
    ?rest_m owl:someValuesFrom ?proc .
};

SPARQL
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/v1.0.0/layerhorizon#>
SELECT DISTINCT ?value ?label lang(?label)
#SELECT ?p ?o
#SELECT ?value
WHERE {
    glosis_lh:SiltValue rdfs:subClassOf ?rest .
    ?rest owl:onProperty qudt:unit .
    ?rest owl:hasValue ?value .
#    ?value ?p ?o .
    ?value rdfs:label ?label . 
#    FILTER (langMatches(lang(?label),"en-us"))
    FILTER(lang(?label) = 'en') .
};


