# These queries are meant to be run through iSQL. Remove the SPARQL prefix and
# ; suffix to run them directly through a SPARQL end-point.

# Observable properties for Surface

SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_su:  <http://w3id.org/glosis/model/v1.0.0/surface#>
SELECT ?query
WHERE {
    ?obs rdfs:subClassOf sosa:Observation .
    ?obs rdfs:subClassOf ?rest .
    ?obs rdfs:subClassOf ?rest_c .
    ?rest owl:onProperty sosa:hasFeatureOfInterest .
    ?rest owl:allValuesFrom glosis_su:GL_Surface .
    ?rest_c owl:onProperty sosa:observedProperty .
    ?rest_c owl:hasValue ?p .
    ?p rdfs:label ?l .
    BIND (CONCAT('INSERT INTO core.property_desc_surface (label, uri) VALUES (\'', ?l,
          '\', \'', ?p, '\');') AS ?query)
}
;

# Observable properties for Plot
SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_sp:  <http://w3id.org/glosis/model/v1.0.0/siteplot#>
SELECT ?query
WHERE {
    ?obs rdfs:subClassOf sosa:Observation .
    ?obs rdfs:subClassOf ?rest .
    ?obs rdfs:subClassOf ?rest_c .
    ?rest owl:onProperty sosa:hasFeatureOfInterest .
    ?rest owl:allValuesFrom ?u .
    ?u owl:unionOf ?set . 
    ?set rdf:rest*/rdf:first ?elements .
    FILTER (glosis_sp:GL_Plot IN (?elements)) .
    ?rest_c owl:onProperty sosa:observedProperty .
    ?rest_c owl:hasValue ?p .
    ?p rdfs:label ?l .
    BIND (CONCAT('INSERT INTO core.property_desc_plot (label, uri) VALUES (\'', ?l,
          '\', \'', ?p, '\');') AS ?query)
}
;

# Observable properties for Profile
SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_pr:  <http://w3id.org/glosis/model/v1.0.0/profile#>
SELECT ?query
WHERE {
    ?obs rdfs:subClassOf sosa:Observation .
    ?obs rdfs:subClassOf ?rest .
    ?obs rdfs:subClassOf ?rest_c .
    ?rest owl:onProperty sosa:hasFeatureOfInterest .
    ?rest owl:allValuesFrom glosis_pr:GL_Profile .
    ?rest_c owl:onProperty sosa:observedProperty .
    ?rest_c owl:hasValue ?p .
    ?p rdfs:label ?l .
    BIND (CONCAT('INSERT INTO core.property_desc_profile (label, uri) VALUES (\'', ?l,
          '\', \'', ?p, '\');') AS ?query)
}
;

# Observable properties for Profile Element
SPARQL
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX glosis_lh:  <http://w3id.org/glosis/model/v1.0.0/layerhorizon#>
SELECT ?query
WHERE {
    ?obs rdfs:subClassOf sosa:Observation .
    ?obs rdfs:subClassOf ?rest .
    ?obs rdfs:subClassOf ?rest_c .
    ?rest owl:onProperty sosa:hasFeatureOfInterest .
    ?rest owl:allValuesFrom ?u .
    ?u owl:unionOf ?set . 
    ?set rdf:rest*/rdf:first ?elements .
    FILTER (glosis_lh:GL_Layer IN (?elements)) .
    ?rest_c owl:onProperty sosa:observedProperty .
    ?rest_c owl:hasValue ?p .
    ?p rdfs:label ?l .
    BIND (CONCAT('INSERT INTO core.property_desc_element (label, uri) VALUES (\'', ?l,
          '\', \'', ?p, '\');') AS ?query)
}
;

